FROM alpine:3.10.3
MAINTAINER berkyavuz
USER root

RUN apk update
RUN apk add net-tools
RUN apk add wget
RUN apk add curl
RUN apk add nano

CMD [ "echo"," Recommended usage -> docker run -it berkyavuz/alpine-for-test sh"]
